### ISSUE TITLE
Workflow support

### ISSUE THREAD

**Issue by bradvido** [citrix/ShareFile-Java#13]
There is currently no support for Workflows API in this SDK.

http://api.sharefile.com/rest/docs/resource.aspx?name=Workflows

**Comment by rgmills** [comment]
@bradvido Hi Brad,  sorry for the late response.  We are working on a few tweaks to get the updated APIs available.

**Comment by NileshPawarCitrix** [comment]
@bradvido  we have released the latest code to github today with the WorkFlow support and also uploaded the .jar files to maven (build version 3.1.5)  Please let us know once you are able to use the workflow api or any more information if required.
